version: "2"
services:
  website-aio:
    restart: unless-stopped
    image: "ghcr.io/natant-network/website-aio-docker:master"
    ports:
    #IMPORTANT: DO NOT CHANGE THE 8080 PART ONLY CHANGE THE 90 PART
      - 90:8080
